# Bug related labels
- name: bug
  color: d73a4a
  description: Something isn't working

- name: critical
  color: b60205
  description: Critical bug that breaks core functionality

- name: ui-bug
  color: f9d0c4
  description: User interface or styling issues

# Enhancement labels
- name: enhancement
  color: a2eeef
  description: New feature or request

- name: improvement
  color: 84b6eb
  description: Enhancement to existing feature

- name: ui-enhancement
  color: c5def5
  description: User interface improvements

# Priority labels
- name: priority-high
  color: d93f0b
  description: High priority issue

- name: priority-medium
  color: fbca04
  description: Medium priority issue

- name: priority-low
  color: 0e8a16
  description: Low priority issue

# Type labels
- name: question
  color: d876e3
  description: Further information is requested

- name: documentation
  color: 0075ca
  description: Improvements or additions to documentation

- name: duplicate
  color: cfd3d7
  description: This issue or pull request already exists

- name: wontfix
  color: ffffff
  description: This will not be worked on

# Component labels
- name: recipes
  color: fef2c0
  description: Related to recipe management

- name: ingredients
  color: c2e0c6
  description: Related to ingredient/pantry management

- name: menu
  color: f9c2ff
  description: Related to menu planning features

- name: auth
  color: 0052cc
  description: Related to authentication

- name: database
  color: 5319e7
  description: Related to database or data storage

- name: mobile
  color: ff9500
  description: Mobile-specific issues

- name: dark-mode
  color: 1d1d1d
  description: Related to dark mode functionality
